name: projects
description: "A new Flutter project with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^4.1.0

  # Firebase Authentication
  firebase_auth: ^6.0.2

  # Firestore Database
  cloud_firestore: ^6.0.1

  # Firebase Storage (compatible with firebase_core 4.x)
  firebase_storage: ^13.0.1

  # Image Picker
  image_picker: ^1.1.1

  # Firebase Analytics
  firebase_analytics: ^12.0.1

  # Firebase Messaging
  firebase_messaging: ^16.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
