name: projects
description: "A new Flutter project with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # Firebase Core (must have)
  firebase_core: ^3.15.2

  # Firebase Authentication
  firebase_auth: ^5.7.0

  # Firestore Database
  cloud_firestore: ^5.4.4

  # Firebase Analytics (optional but recommended)
  firebase_analytics: ^11.3.0

  # Firebase Messaging (optional for push notifications)
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


